CREATE TABLE "ACTIVITY" (
	"ID" TEXT,
	"YEAR" NUMBER NOT NULL,
	"MONTH" NUMBER NOT NULL,
	"DAY" NUMBER NOT NULL,
--
	"NAME" TEXT NOT NULL,
        "COMMENT" TEXT NOT NULL,
        "TICKET" TEXT NOT NULL,
        "SPENT_HOURS" NUMBER NOT NULL,
        "SPENT_MINUTES" NUMBER NOT NULL,

        "FLAGS" TEXT NOT NULL,
	PRIMARY KEY("ID")
);
